### ISSUE TITLE
Referrer-Policy headers strict-origin affect password protected pages

### ISSUE THREAD

**Issue by fjaviero** [Azure/wordpress-linux-appservice#103]
Hello Team.

I have two questions.

About the issue described in the title, I was informed you going to remove the policy, but, I will like to confirm if it will be delete o change for other _Referrer-Policy_?.

Too, I will like to know what was the reason to use or set the strict-origin policy? Our client say the password protect redirect error not happened before, so, trusting in they word, I suppose the policy not exist before, o even the _spec-setting.conf_ file not exist before.

I will appreciate your help.

**Comment by ZubaeyrMSFT** [comment]
We have added Referrer-Policy header to enhance security. Users can set the value of Referrer-Policy based on their requirement. You can customize it to use **same-origin** or any other policy that works for your use case. You can check out this document to understand more about referer policy: https://web.dev/referrer-best-practices/

To configure Nginx for WordPress on App Service, please see this documentation: https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md
