### ISSUE TITLE
Can not get webp images work

### ISSUE THREAD

**Issue by emmigereb** [Azure/wordpress-linux-appservice#105]
Hi
I followed step by step this: https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_WebPimages_support.md but i can´t get them to work.
<img width="722" alt="Screenshot 2023-09-05 at 01 43 38" src="https://github.com/Azure/wordpress-linux-appservice/assets/1269563/01ca18eb-07c2-458f-9c2f-764a91517529">

**Comment by samrueby** [comment]
Hi! I would check the app service logs and see if startup.sh is failing to execute.

**Comment by emmigereb** [comment]
Yes, I think it does. And for almost all our App services.

**Comment by gokaycagri** [comment]
same problem

**Comment by ZubaeyrMSFT** [comment]
The document seems to be slightly outdated because of which it is not working. I will test the new steps and update it soon.

**Comment by ZubaeyrMSFT** [comment]
@gokaycagri, @emmigereb 

WebPI support has been enabled by default within the image. You can restart your App Service to pull the latest changes. 

**Note:** Please ignore the previous documentation (as it is no longer required), and also remove any custom startup script for the same (if you have added any).

**Comment by ZubaeyrMSFT** [comment]
Closing this issue. Thanks!!
