### ISSUE TITLE
Sending email containing a html body

### ISSUE THREAD

**Issue by rduque1** [Azure/wordpress-linux-appservice#107]
Hi,

I installed the plugin `Azure Wordpress-on-Linux-App-Service-plugins main app_service_email.zip` and followed the installation steps described in the [WordPress Email Integration](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_email_integration.md), and this works.

However the emails containing a HTML body are send as plain text.
How can we send them as HTML?

Thanks

**Comment by rabollin** [comment]
@rduque1 - we will be adding that support shortly, in weeks time.

**Comment by bmanjwani** [comment]
@rduque1 - Can you tell us the steps to replicate the scenario where emails containing a HTML body are send as plain text ?

**Comment by rduque1** [comment]
We use the plugin [Ultimate member plugin](https://wordpress.org/plugins/ultimate-member/).
This plugin allows to send emails at registration, approval, ... etc. You can choose to specify an HTML or text body.

But if I am correct in the code of the plugin you never specify in the post request to the endpoint that the content is HTML. Because in the documentation for the CLI tool for the Azure communication services you the arguments given to the CLI command are different when it's plain text or html.

**Comment by bmanjwani** [comment]
We have updated our plugin to support the html content.
You can download the zip file of latest version of the plugin using this [link](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FAzure%2FWordpress-on-Linux-App-Service-plugins%2Ftree%2Fmain%2Fapp_service_email).
Please let us know if email integration is working for you now.

**Comment by rduque1** [comment]
@bmanjwani it's working. Thank you
