### ISSUE TITLE
Question about Azure Blob Storage with WordPres

### ISSUE THREAD

**Issue by emmigereb** [Azure/wordpress-linux-appservice#109]
Hello
What other solution or plugin do you recommend other than W3 Total Cache to connect to Azure Blob Storage?
I am trying out this one: https://wordpress.org/plugins/windows-azure-storage/ but it uploads the files like year/month instead of wp-content/uploads/year/month which is not working for us.

W3 Total Cache did a good job but we rather use WP Rocket as a caching plugin. 

![Screenshot 2023-09-08 at 11 52 24](https://github.com/Azure/wordpress-linux-appservice/assets/1269563/22686b14-21b7-4c07-a920-749c6ec5edc3)

**Comment by samrueby** [comment]
W3 Total Cache offers a bunch of features that I believe can all be turned off piecemeal. I think you could use WP Rocket for the caching features you're looking for, while only using W3 Total Cache for the blob storage feature.

**Comment by emmigereb** [comment]
Thanks for the answer. Not a possibility to use both W3 Total Cache and WP Rocket. You get a message that the two plugins are not compatible and you need to deactivate one of the.

Is there any other plugin för Azure storage and Wordpress that you know of?

**Comment by samrueby** [comment]
Not that I know of, but I think the warning can be safely ignored. If you were using both plugins with their features activated, yes, it could cause problems. However if everything is otherwise off in W3 Total Cache, there should be no issues.

**Comment by emmigereb** [comment]
Thanks.

**Comment by rabollin** [comment]
@emmigereb - Are you looking for any further information on this or can close the issue.

**Comment by rabollin** [comment]
Closing the issue as there is pending action item from us.
