### ISSUE TITLE
Where is the Docker source file for the wordpress-alpine-php Docker Image

### ISSUE THREAD

**Issue by lintaonz** [Azure/wordpress-linux-appservice#111]
Hi,

Where can I find the docker source file for the `wordpress-alpine-php` Docker Image? 

* The github repo [Azure-App-Service/wordpress-alpine-php](https://github.com/Azure-App-Service/wordpress-alpine-php) haven't been updated for 6 years.
* The docker hub [appsvcorg/wordpress-alpine-php](https://hub.docker.com/r/appsvcorg/wordpress-alpine-php) image is 2 years old.

Thanks,

Tao

**Comment by ZubaeyrMSFT** [comment]
@lintaonz 
https://github.com/Azure-App-Service/ImageBuilder/tree/master/GenerateDockerFiles/wordpress/wordpress
