### ISSUE TITLE
Azure App Service Migration plugin - file exceeds 4GB

### ISSUE THREAD

**Issue by 0GiS0** [Azure/wordpress-linux-appservice#114]
I was trying to follow the steps for the migration plugin: https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/WordPress_Migration_Plugin.md
 
But the problem is the export file is too big (6.2GB) to import it in the new Wordpress and the plugin complains about it: 

<img width="2111" alt="image" src="https://github.com/Azure/wordpress-linux-appservice/assets/175379/88180a2b-a074-4fa9-9cfc-735393d7abff">

Do we have an alternative for this?
 
Thank you so much!!!

**Comment by rabollin** [comment]
The plugin which is published works only for 4 GB, we are still working on next version of the plugin that will support larger size content. ETA to be published.

**Comment by ZubaeyrMSFT** [comment]
This plugin is no more supported. Closing this thread.
