### ISSUE TITLE
HTML emails getting mangled

### ISSUE THREAD

**Issue by michaelassad** [Azure/wordpress-linux-appservice#118]
The email plugin is working great after some wrangling through all the Azure screens. However, my HTML emails from WordPress are getting mangled. Looks like additional < br > tags are getting inserted somewhere along the line. Is there a way around that?

**Comment by bmanjwani** [comment]
@michaelassad , Can you share the screenshot of the emails which is being mangled?  Are you sending emails using some plugin ?

**Comment by michaelassad** [comment]
I'm using WP Forms and WooCommerce. For example, the WooCommerce order email gets spread out like this:

![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/5742fe7c-0016-4472-b7fe-496ecc175073)
![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/2017735c-76ec-4111-afa0-0e2f8ac3a8d5)

**Comment by michaelassad** [comment]
WP Forms is like this:

![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/1b1314fd-a327-4b18-9703-e5a2bdc4c6b0)
![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/abc1b15d-ed91-44c9-86f3-160fe00aa49b)
![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/9556301c-1699-4fc5-9674-e43651916682)
[...]
![image](https://github.com/Azure/wordpress-linux-appservice/assets/11052195/b56b17f6-b020-478c-8c95-6e7ab4c04e35)

**Comment by michaelassad** [comment]
I have confirmed the same results on a brand new Wordpress App Service install in the Central US location.

**Comment by bmanjwani** [comment]
@michaelassad , Can you consider using a different plugin in place of WP Forms and see if that works for you?

**Comment by michaelassad** [comment]
My bigger concern is the WooCommerce emails. I can send everything in plain text for now, but would like to know there's a path to fix this before fully committing to the App Service model.

**Comment by michaelassad** [comment]
Is there a contact form plugin that you recommend?

**Comment by michaelassad** [comment]
Obvious Answer: SendGrid. The Azure Communications Services isn't there yet.

**Comment by bmanjwani** [comment]
Thank you for your feedback. Azure's email communication service has its unique strengths, but I understand your concern. SendGrid is a dedicated email service provider, while azure's offering is integrated with a broader cloud platform. We are continually improving our service and making it stronger choice for businesses. 

Please provide your email address so that I can book a slot and review your setup to further assist you.

**Comment by michaelassad** [comment]
I would prefer to do everything within Azure services but there are two key things missing from the current implementation for using with WordPress / WooCommerce:

1) HTML emails don’t work well - you can’t have customers of your eCommerce store getting mangled emails

2) The reply-to population for emails doesn’t work. So for example, if someone emails you from a website contact form, you can’t simply reply to that email to respond to them. This is a must have. 

So hopefully these two issues are resolved and I can avoid the third party service. In the meantime the sendgrid app for azure with an smtp plugin works great! Thanks for your help!!

**Comment by michaelassad** [comment]
I would prefer to do everything within Azure services but there are two key things missing from the current implementation for using with WordPress / WooCommerce:

1) HTML emails don’t work well - you can’t have customers of your eCommerce store getting mangled emails

2) The reply-to population for emails doesn’t work. So for example, if someone emails you from a website contact form, you can’t simply reply to that email to respond to them. This is a must have. 

So hopefully these two issues are resolved and I can avoid the third party service. In the meantime the sendgrid app for azure with an smtp plugin works great! Thanks for your help!!
