### ISSUE TITLE
Errors in Azure Email Logs - emails not getting sent

### ISSUE THREAD

**Issue by michaelassad** [Azure/wordpress-linux-appservice#119]
I can send a message fine from the Communication Service 'Try Email', but when I tried to send from a form on my site, I get this error after a long delay:

cURL error 28: Connection timed out after 5000 milliseconds[Click here](https://learn.microsoft.com/en-us/azure/communication-services/support) for more support.

**Comment by bmanjwani** [comment]
@michaelassad did you try sending email directly from WordPress site (e.g., forgot password, add new user) without using any plugin?
Also can you provide more information 
1. Email integration is enabled and configured out of the box in your site or did you setup using manual steps provided [here](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_email_integration.md) 
2. Are you configuring custom domain or azure managed domain?

**Comment by michaelassad** [comment]
I figured this one out - I had a Firewall set up in Azure that was blocking the emails.

**Comment by michaelassad** [comment]
Yes
