### ISSUE TITLE
Startup script lacks permissions to modify nginx config files

### ISSUE THREAD

**Issue by PatrykPlewaOfficial** [Azure/wordpress-linux-appservice#121]
Due to this [instruction](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md#update-nginx-configuration), it should be possible to modify nginx config files.

However, the startup script (`/home/dev/startup.sh`) is run as the `nobody` user which has insufficient permissions to modify nginx files owned by `root`:

![image](https://github.com/Azure/wordpress-linux-appservice/assets/47867089/4477ca2e-b1d1-4d93-939e-0de14a974961)

**Comment by ZubaeyrMSFT** [comment]
Hi @PatrykPlewaOfficial, startup script is run by the root user. It should have sufficient permissions to modify the nginx config files. Can you please post your error or content of startup.sh file?

**Comment by ZubaeyrMSFT** [comment]
@PatrykPlewaOfficial Please share the steps to reproduce the issue

**Comment by PatrykPlewaOfficial** [comment]
Weird situation. I was diagnosing why my changes were not being applied so I inserted this line into the shell file
``` sh
whoami > /home/site/test
```
and I saw `nobody` in the test file.

However the other day after a restart it changed the content of the file with `root`.

I guess everything works as desired then. Can be closed. Just one weird result.
