### ISSUE TITLE
wordpressonappservice@microsoft.com not working

### ISSUE THREAD

**Issue by xzuttz** [Azure/wordpress-linux-appservice#129]
Hi,

According to the instructions provided in the following guide available at:

[WordPress Migration Plugin Guide](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/WordPress_Migration_Plugin.md)

In the event of encountering errors, you can contact us via email at wordpressonappservice@microsoft.com.

However, please note that when attempting to send an email to the aforementioned address, Google returned the following message:

"The response from the remote server was:
550 5.4.1 Recipient address rejected: Access denied. [MWH0EPF0009FF17.namprd00.prod.outlook.com](http://mwh0epf0009ff17.namprd00.prod.outlook.com) 2024-01-24T22:38:13.902Z 08DC137C703AD6CD"

**Comment by pauljohnstone** [comment]
Would be great to see a support email available...or is it best to post issue & questions here?

**Comment by ZubaeyrMSFT** [comment]
Hello @xzuttz, @pauljohnstone, the correct support email is wordpressonazure@microsoft.com.
