### ISSUE TITLE
Intl: is not installed, or has been disabled.

### ISSUE THREAD

**Issue by arisniko1** [Azure/wordpress-linux-appservice#135]
Hello! I don't know if it's an issue per se but whatever I have tried I cannot install intl to my website. Pecl install can't build it, with apk add it does install it but the installation is not persistent when I have to restart the app. I follow every official and unofficial guide I have found but no persistence whatsoever.

**Comment by samrueby** [comment]
Persistance can be solved by adding the commands to install in the startup script.

**Comment by arisniko1** [comment]
Hello! It doesn't work with a startup script either... I follow this guide: [https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_adding_php_extensions.md](url) and when the app restarts after step 7 the module is nowhere to be found...

**Comment by samrueby** [comment]
That guide doesn't mention the startup script. That guide takes a module and places it within /home/site, which is persisted between restarts. If it's not, then WEBSITES_ENABLE_APP_SERVICE_STORAGE should be set to true.

Instead, I recommend following [this guide](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md) to use `apk add` in a startup script, which you mentioned works as you expect.

**Comment by arisniko1** [comment]
I have checked and double-checked everything to no avail. I have managed to have it installed with the startup script on /home/dev/ every time it restarts but the website doesn't see it as enabled. It is just installed. Any advice?

**Comment by ZubaeyrMSFT** [comment]
Closing this as duplicate, as there is another recent thread.
