### ISSUE TITLE
Export frozen @ 20% with no error

### ISSUE THREAD

**Issue by WhiteyC** [Azure/wordpress-linux-appservice#136]
When performing All-In-One WP Migration, the export as file freezes at around 20% for many hours and no error is offered. How can I debug the issue? 

Site is fully up to date with updates.

Attached screen shot.

![WordPress_Export_Frozen](https://github.com/Azure/wordpress-linux-appservice/assets/23065270/f9de1276-d82d-4801-add3-bcaca392a372)

**Comment by samrueby** [comment]
Does your web server prevent long-running requests? My first assumption is that the process is being terminated via timeout.

**Comment by WhiteyC** [comment]
Highly unlikely as this is an Azure WP App Service and this migration tool is proposed by Azure as the preferred method and no mention in the documentation of any such setting required. The migration export also corrupts the WP site and I have to revert to a backup to restore the site.

**Comment by ZubaeyrMSFT** [comment]
Please raise a support ticket with W3TC plugin on this. https://github.com/BoldGrid/w3-total-cache/issues
This is a third-party plugin and doesn't fall within our support.
