### ISSUE TITLE
Wordpress on Azure appservice email integration plugin missing

### ISSUE THREAD

**Issue by TTaylorTCC** [Azure/wordpress-linux-appservice#138]
I am following the steps to set up Wordpress app service integration (https://techcommunity.microsoft.com/t5/apps-on-azure-blog/wordpress-on-azure-appservice-email-integration/ba-p/3890486), but on step 8:
Download the App service email plugin from here: [Click here](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FAzure%2FWordpress-on-Linux-App-Service-plugins%2Ftree%2Fmain%2Fapp_service_email), there is no plugin.
Is this still an option? Where is this plugin. Everything else up until this step works, but I'm stuck trying to connect to WordPress because there isn't a plug in.
Thank you

**Comment by seifadel25** [comment]
same problem :(((((

**Comment by bmanjwani** [comment]
@seifadel25 and @TTaylorTCC , we have updated our official wordpress image with the app service email plugin, these images will have the plugin installed and activated by default. Can you please share which wordpress image you are using ?

Please feel free to drop an email to **wordpressonazure@microsoft.com**, if you need more assistance in this regard.

**Comment by paynecodes** [comment]
Where can we get the plugin directly? I'm having trouble finding it after we did a migration of an existing site wiped out our plugins folder.

**Comment by seifadel25** [comment]
@bmanjwani yes you're right i figured that out randomly when was checking plugins, Thank you

**Comment by alessandro-hic** [comment]
I have the plugin deleted by an import/restore from another website, so I would like to re-install the plugin, how can I do without reinstalling the image and do everything manually? 

Thanks

**Comment by pauljohnstone** [comment]
Is the plugin still supported?
[Page not found · GitHub](https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/tree/main/app_service_email)

**Comment by bmanjwani** [comment]
@pauljohnstone / @alessandro-hic / @seifadel25 / @TTaylorTCC / @paynecodes 
We've made some changes to the location of the App Service Email Plugin file. You can now download the plugin from our GitHub repository at the following link: [GitHub Repo Link](https://github.com/Azure/wordpress-linux-appservice/blob/main/Plugins/app_service_email/1.1.0/app_service_email.zip)

Additionally, we've updated the documentation to reflect this change. You can find the updated documentation with the correct link here: [Documentation Link](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/wordpress-on-azure-appservice-email-integration/ba-p/3890486)

**Comment by pauljohnstone** [comment]
@bmanjwani Thanks for the update please keep me posted on this
