### ISSUE TITLE
Azure Communication Services Sending File Attachments

### ISSUE THREAD

**Issue by pauljohnstone** [Azure/wordpress-linux-appservice#142]
Are there any known issues with Azure communication services not sending file attachments? Currently when sending emails by web form the file is not attachments.

- The WordPress setup is using plugin Contact Form 7, very simple implementation.
- And the Azure Email Log plugin which is displaying Success when sending emails. 
- Also has the repo for the plugin been moved [Page not found · GitHub](https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/tree/main/app_service_email) 

Are there any further setup to send attachments by Azure communication services?

**Comment by pauljohnstone** [comment]
It looks like that the Azure Plugin is not set-up to handle email attachments, based on my quick review of the following files.

class-azure_app_service_email-controller.php
class-azure_app_service_email-logger.php

**Comment by bmanjwani** [comment]
@pauljohnstone , We've made updated the plugin's functionality to accommodate attachments. However, as of now, it doesn't support the Contact Form 7 plugin for sending emails with attachments. But we've added it to our backlog for implementation. Thank you for bringing this to our attention, and we'll keep you updated on our progress. 

And now you can download the plugin from below GitHub link : 
https://github.com/Azure/wordpress-linux-appservice/blob/main/Plugins/app_service_email/1.1.0/app_service_email.zip

We have updated the link in our documentation as well.

Thanks.

**Comment by pauljohnstone** [comment]
Great news that has been added to the backlog and please keep me updated.
Does the update support any of the WP current plugins?

**Comment by pauljohnstone** [comment]
@bmanjwani Just a note best to update the plugin link & version 1.1.0

![image](https://github.com/Azure/wordpress-linux-appservice/assets/6846803/8d471d5c-55b7-4c10-bc29-1d336dd72488)

**Comment by bmanjwani** [comment]
@pauljohnstone We have already updated the plugin version. Maybe it will take 1-2 weeks' time to reflect in the customers sites. We've conducted tests on few WooCommerce plugins, including ones that attach PDF invoices to emails, and everything worked smoothly. One notable plugin we tested is "**PDF Invoices & Packing Slips for WooCommerce.**"

**Comment by pauljohnstone** [comment]
Is auto update on the roadmap?
And Visit plugin site, is still pointed to https://github.com/Azure/Wordpress-on-Linux-App-Service-plugins/tree/main/app_service_email

**Comment by pauljohnstone** [comment]
And any update on Contact Form 7 plugin for sending emails with attachments?

**Comment by bmanjwani** [comment]
@pauljohnstone 

- Yes auto update of email plugin is on the roadmap but it might take some time , we will keep you posted about these changes.
- And thanks for pointing out the **visit plugin url**, we will do the needful.
- As of now there no update on contact form 7 supportability, it is not prioritized as of now.

**Comment by ZubaeyrMSFT** [comment]
@bmanjwani, can you update on this and close the thread?

**Comment by bmanjwani** [comment]
@pauljohnstone  updated the **visit plugin url** to point it to the right repository.
