### ISSUE TITLE
Application Insights for WordPress

### ISSUE THREAD

**Issue by pauljohnstone** [Azure/wordpress-linux-appservice#148]
Hi All, 

Just reaching out here to see if anyone knows anything about the road map for Application Insights for WordPress looks like the plugin development on github was archived on Oct 12 2022.
Are there any plans on the roadmap to move Application Insights into the App Services template so there is no further plugin required?

https://github.com/microsoft/ApplicationInsights-WordPress

**Comment by ZubaeyrMSFT** [comment]
Hello @pauljohnstone

Currently, we don't have out of the box support for Application Insights with WordPress. Please send an email on wordpressonazure@microsoft.com. Someone from the team should be able to guide you.
