### ISSUE TITLE
The 404 page breaks if the W3 Total Cache plugin is activated with its default settings

### ISSUE THREAD

**Issue by vienleidl** [Azure/wordpress-linux-appservice#150]
When the W3 Total Cache plugin is activated and its CDN configuration is enabled by default, the design of 404 page is broken, it seems to be that the loading of theme, CSS and JS files makes the 404 page crashing. As I had a look at the URLs of all corrupted files (.js, .css..), I found that the WordPress website tried to load those files from Azure Blob Storage, which only hosts the images files (blob_container_name/wp-content/uploads).

![image](https://github.com/Azure/wordpress-linux-appservice/assets/97711647/4c465b90-9b27-4301-9416-6ecf39daea0b)

**Workaround**
Untick on the 3 following options to temporarily disable caching and hosting for theme, CSS and JS files. Then, it will work again.

![image](https://github.com/Azure/wordpress-linux-appservice/assets/97711647/0ab05565-73d8-4340-8a82-e3552802074b)

At the beginning, we prefer to use WP Rocket plugin than W3 Total Cache, because sometimes the W3 Total Cache generates some weird issues and we're not big fans of it. But the WP Rocket seems to not support hosting and caching uploaded images like the W3 Total Cache, and I don't see any options for integrating with Azure Storage Account. AFAIK, both of them should not be activated at the same time, the compatibility warning message will appear.

**Comment by ZubaeyrMSFT** [comment]
Hello @vienleidl, can you please elaborate on the errors you are facing? Are these CORS error or 404 not found errors? 

At Azure CDN level, we add rules to ensure that only the URIs that match **/<blob_container_name/wp-contents/uploads** prefix are forwarded to Azure Blob Storage. Rest of them are modified accordingly and forwarded to Web App.

**Comment by ZubaeyrMSFT** [comment]
Hi @vienleidl, thank you for raising this issue. We have pushed a fixed that will be available for new deployments in next weeks. Furthermore, I have added a documentation about this issue: [CORS Issue With Azure CDN / FrontDoor or Azure Blob Storage](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/cors_issue_with_azure_cdn_frontdoor_blob.md#cors-issue-with-azure-cdn--frontdoor-or-azure-blob-storage)
