### ISSUE TITLE
Blob media uploaded in Azure Portal not visible on app

### ISSUE THREAD

**Issue by victorlin** [Azure/wordpress-linux-appservice#156]
First off, thank you for the various documentation in this repo – it's been helpful in setting up and configuring a Wordpress site on Azure for the first time.

Following [this advice](https://github.com/Azure/wordpress-linux-appservice/blob/b23b80df28d368f323167d432454ba711a84dc87/WordPress/wordpress_azure_blob_storage.md?plain=1#L31):

> You can upload media files to the blob storage using the WordPress Admin dashboard (Media -> Add New) or the Azure Portal. In Azure Portal, you can find the storage account resource in the same resource group where your WordPress App Service is deployed. Go to the storage account and select **'Containers'** under **'Data storage'** section. Open the appropriate blob container and click on Upload option shown at the top.

I am able to upload media files using the Wordpress Admin dashboard and it appears in Blob storage.

However, when I upload a media file directly to the storage account in Azure portal as `wp-content/uploads/2024/07/test.png`, it does not show up in the Wordpress Admin dashboard nor filesystem (expecting `/home/site/wwwroot/wp-content/uploads/2024/07/test.png`).

Is there some extra configuration that I am missing?

**Comment by saisubodhMSFT** [comment]
@victorlin  When media files are uploaded to WordPress, a reference to it is stored in the database. When you upload a media file to blob storage this reference in database is not created because of which you can't see the files in WordPress dashboard or filesystem.

Thanks for pointing out this. We will correct our documentation.

**Comment by saisubodhMSFT** [comment]
If you still want this to work where files uploaded to blob storage are detected in WordPress, you can explore this blog on "Add from Server" plugin

**Comment by victorlin** [comment]
Thanks, for clarifying, that makes sense!
