### ISSUE TITLE
App Service Email version 1.1.0 vs. 1.2.0

### ISSUE THREAD

**Issue by victorlin** [Azure/wordpress-linux-appservice#159]
App Service Email 1.2.0 was added to this repo in #154.

However, my recent deployment still comes with App Service Email plugin version 1.1.0, and that version is still referenced in the docs:

https://github.com/Azure/wordpress-linux-appservice/blob/7e593b214c040afbf2c9937fb365f4d870b9b425/WordPress/wordpress_email_integration.md?plain=1#L45

Questions:

1. Is there any functional difference between the two versions?
2. Is it safe to manually update to version 1.2.0 by unzipping the folder to replace `/home/site/wwwroot/wp-content/plugins/app_service_email`?

**Comment by bmanjwani** [comment]
@victorlin

In a few weeks, you will see deployments with the App Service Email Plugin version 1.2.0. Here are the key points:

**Version Difference**: Version 1.2.0 supports configuring managed identity with Azure Communication Services email. This is the primary difference from the previous version.
2. It is safe to upgrade to version 1.2.0.

If you are not configuring managed identity with your WordPress app, there will be no noticeable difference between the plugin versions.
 Documentation regarding the new features and configuration will be published soon.

**Comment by ZubaeyrMSFT** [comment]
Hi @victorlin 

Added a change log documentation [CHANGE_LOG.md](https://github.com/Azure/wordpress-linux-appservice/blob/main/Plugins/app_service_email/CHANGE_LOG.md) that lists down the changes between different versions. Also, yes, it is safe to upgrade.
