### ISSUE TITLE
location of ARM/Bicep files for the installation?

### ISSUE THREAD

**Issue by AaronSaikovski** [Azure/wordpress-linux-appservice#17]
the repo seems to be missing the actual scripts to do the deployment such as ARM/Biceo templates.
can you share these??

**Comment by btardif** [comment]
The best approach is to do this through the portal first: [WordPress on Linux App Service](https://aka.ms/linux-wordpress)

You can export the generated template as part of the create flow:

![image](https://user-images.githubusercontent.com/4119816/195900118-df675943-2e51-46c1-bb79-851ba217f0fe.png)
