### ISSUE TITLE
Folder & File Permission

### ISSUE THREAD

**Issue by pauljohnstone** [Azure/wordpress-linux-appservice#176]
I need to confirm the following regarding folder permissions:

A recent deployment has set the core folder permissions to drwxrwxrwx (777), which is:

`drwxrwxrwx 2 nobody nobody 0 Jul 23 19:04 /home/site/wwwroot/wp-admin/`
`drwxrwxrwx 2 nobody nobody 0 Sep 9 01:32 /home/site/wwwroot/wp-content/`
`drwxrwxrwx 2 nobody nobody 0 Jul 24 06:16 /home/site/wwwroot/wp-includes/`

This appears to be due to the mounting of local storage, and from my understanding, folder or file permissions cannot be changed in any way. Please correct me if I am mistaken.

By setting the WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED environment variable to false, the folder permissions will be reset to 755 as follows:

`drwxr-xr-x 9 nobody nobody 4096 Sep 11 02:18 /home/site/wwwroot/wp-admin/`
`drwxr-xr-x 9 nobody nobody 4096 Sep 11 02:20 /home/site/wwwroot/wp-content/`
`drwxr-xr-x 30 nobody nobody 12288 Sep 11 02:34 /home/site/wwwroot/wp-includes/`

Please confirm if my understanding is correct.

**Comment by BlackRider97** [comment]
Yes, that's correct. Steps of feature `WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED` are documented [here](https://github.com/Azure/wordpress-linux-appservice/blob/c0b412da1632d43cee53b83d0f9a7a8831f99277/WordPress/enabling_high_performance_with_local_storage.md#L4-L37) 

However, I wanted to clarify what's the issue with 777 directory permission as it does not allow any user to access these files as file system is protected by app service. You may find similar issue explanation [here](https://stackoverflow.com/questions/78449412/cannot-change-permission-of-azure-app-service-linux-directory)
I understand permission 777 looks but it's completely acceptable in case of App Service. 

[Here ](https://learn.microsoft.com/en-us/answers/questions/1723620/how-do-i-change-file-permissions-for-wordpress-in)is more detailed explanation of the issue

**Comment by BlackRider97** [comment]
Related to https://github.com/Azure/wordpress-linux-appservice/issues/80

**Comment by pauljohnstone** [comment]
@BlackRider97 


When the WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED setting is changed to false, the folder permissions are automatically reset to 755. Can you confirm if this is correct?

If that is the case, I have noticed that folder permissions did not change after the setting was set to false. What could potentially be causing this issue?

Thank you for the reference links—I had reviewed them prior to posting my comment.

And yes, I completely understand that the App Service file system is protected. However, when you're working with clients who continually encounter system vulnerabilities and then see that their directory has 777 permissions, they start asking questions.
