### ISSUE TITLE
Azure Portal says Alpine PHP 8.2, 8.3 EOL

### ISSUE THREAD

**Issue by samrueby** [Azure/wordpress-linux-appservice#180]
I would have made this a PR instead but perhaps some discussion should bring more clarity.

The README in this repo currently says that Alpine Linux images 8.2 & 8.3 are "✅ Supported and recommended". I don't think that's true. At this moment in the Azure Portal I see this in the Configuration blade of my App Service:
![Image](https://github.com/user-attachments/assets/91984c75-fd45-493c-ba43-3bf849563f3a)
The image above indicates that Alpine 8.2 & 8.3 is EOL. 

Please correct me if I'm wrong but I think EOL (End of Life) indicates this image is not recommended. I would also think this means it is no-longer supported. 

This blog post: [Transition from Alpine Linux to Debian for WordPress on App Service](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/transition-from-alpine-linux-to-debian-for-wordpress-on-app/ba-p/4264858) says the Alpine stack will only be supported until the end of 2024.

I believe this repo's README should be updated to indicate the Alpine images are not recommended, soon not-to-be-supported, and indicate "⚠️ End of Life" instead.

**Comment by reddyabhishek** [comment]
You are right.

Alpine images are not recommended. They will be supported until the end of 2024.

Please upgrade to PHP 8.2 or PHP 8.3.
