### ISSUE TITLE
Terraform scripts missing from the repo.

### ISSUE THREAD

**Issue by benmthomas** [Azure/wordpress-linux-appservice#181]
The terraform deployment scripts seem to have been removed from the repo in this [PR ](https://github.com/Azure/wordpress-linux-appservice/pull/177) without explanation. Is this not supported in this project anymore?

**Comment by skelso01** [comment]
I miss the terraform files, too. Is this coming back?

Best regards
SK

**Comment by BlackRider97** [comment]
Added again in PR: https://github.com/Azure/wordpress-linux-appservice/pull/183
