### ISSUE TITLE
Adding RediSearch to the existing redis-server instance in mcr.microsoft.com/appsvc/wordpress-debian-php:8.3

### ISSUE THREAD

**Issue by fmnsantos** [Azure/wordpress-linux-appservice#187]
Hello,

I am running an instance of the WordPress on Linux App Services image `mcr.microsoft.com/appsvc/wordpress-debian-php:8.3` on Azure. I would like to add the `redisearch` module to the existing server, listening on 127.0.0.1:6379.

To install the library, I have tried the following:
1) `apt-get update -y && apt-get install -y redis-redisearch`. This installs the `redisearch.so` dynamic library at `/usr/lib/redis/modules/redisearch.so` using the aforementioned Debian package.
2) `echo 'loadmodule /usr/lib/redis/modules/redisearch.so' >> /etc/redis/redis.conf`. This configures the `redis-server` instance to load the `redisearch.so` library on startup.
3) Finally, I restarted the server, as follows: `service redis-server restart`.

To ensure these steps run whenever the container is restarted, I would need to add them to a [post startup script](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/running_post_startup_scripts.md).

The redis server's log shows that the module was, indeed, loaded but, also, that the server failed to start, as 127.0.0.1:6379 is already in use:

> 4477:C 09 Dec 2024 17:24:13.292 * Redis version=7.4.1, bits=64, commit=00000000, modified=0, pid=4477, just started
> 4477:C 09 Dec 2024 17:24:13.292 * Configuration loaded
> 4477:M 09 Dec 2024 17:24:13.310 * monotonic clock: POSIX clock_gettime
> 4477:M 09 Dec 2024 17:24:13.319 * Running mode=standalone, port=6379.
> 4477:M 09 Dec 2024 17:24:13.330 * **<ft> RediSearch version 1.2.0 (Git=)**
> 4477:M 09 Dec 2024 17:24:13.331 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8, 
> 4477:M 09 Dec 2024 17:24:13.358 * <ft> Initialized thread pool!
> 4477:M 09 Dec 2024 17:24:13.359 * **Module 'ft' loaded from /usr/lib/redis/modules/redisearch.so**
> 4477:M 09 Dec 2024 17:24:13.359 # **Warning: Could not create server TCP listening socket 127.0.0.1:6379: bind: Address already in use**
> 4477:M 09 Dec 2024 17:24:13.359 # Failed listening on port 6379 (tcp), aborting.
.

What am I doing wrong? What are the necessary steps to add `redisearch` to the existing image `mcr.microsoft.com/appsvc/wordpress-debian-php:8.3`?

Thanks!

**Comment by fmnsantos** [comment]
Thank you @samrueby.

However, in my startup script I was, indeed, using `service redis-server restart`, which should have stopped and then started the redis-server running on the container. Apparently, this command (alone) was not enough to stop the server and release the bound port 6379.

I had do issue the command `redis-cli shutdown`, followed by `service redis-server start`, after appropriately editing the `/etc/redis/redis.conf` file, to load the redisearch module.

Now it is working.

I will mark this as closed.

**Comment by samrueby** [comment]
Great to hear! I thought it would be something along those lines, since the process you mentioned looked correct.
