### ISSUE TITLE
Add a support for storing WordPress media to Azure Blob Storage

### ISSUE THREAD

**Issue by ltkvien** [Azure/wordpress-linux-appservice#31]
After created WordPress with the [default ARM Template](https://portal.azure.com/#create/WordPress.WordPress), it's cool that the static content of WordPress website is stored in Azure Blob Storage. However, it seems to be not available in Bicep & Terraform files.

**Comment by AaronSaikovski** [comment]
ok thanks will add this to the next release

**Comment by AaronSaikovski** [comment]
done and pending PR
