### ISSUE TITLE
Guide on Modifying PHP settings like PHP Execution Time etc.

### ISSUE THREAD

**Issue by mast3rbow** [Azure/wordpress-linux-appservice#33]
It would be handy to have a guide on how to modify PHP settings like execution time as certain addons want longer periods.

**Comment by rabollin** [comment]
@mast3rbow - Would you be able to share highlevel the different PHP setting being used in your site?

**Comment by mast3rbow** [comment]
an example is php_value max_execution_time which I think by default is 130, but some Wordpress themes want 180.

**Comment by ZubaeyrMSFT** [comment]
If you want to modify the PHP settings, you have to add it as **Application Setting** in your App Service. Please refer to the following document for list of PHP settings available for modification.

https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_application_settings.md#fixed-application-settings

For instance, to change maximum execution time for PHP, you need to add **MAX_EXECUTION_TIME** Application Setting with the desired value. As per the documentation, it cannot be increased beyond 120 seconds.
