### ISSUE TITLE
CORS & CDN Issues 

### ISSUE THREAD

**Issue by JoshuaO** [Azure/wordpress-linux-appservice#46]
There is the same issue (#42) in the closed issue, but I also had the same issue, so I created a new issue.

**Comment by bmanjwani** [comment]
@JoshuaO Browser is complaining about missing "Access-Control-Allow-Origin" header hence preventing the cross origin resource sharing. You can create a rule in the Azure CDN resource to check the Origin header on the request. If it's a valid origin, your rule will set the Access-Control-Allow-Origin header with the desired value. 
Inorder to create a rule in Azure CDN resource follow below steps:
1. Go to your microsoft profile -> then Azure CDN profile.
2. On the CDN profile page, select the endpoint you want to create rules for.
3. Select the Rules Engine tab.
4. Select Add Rule to create a new rule. 
For more details click [here](https://learn.microsoft.com/en-us/azure/cdn/cdn-cors#azure-cdn-standard-profiles)

**Comment by AaronSaikovski** [comment]
Please provide more detail - where is this occurring as ive tested both Bicep and Terraform and there aren't any issues reported. Please clarify

**Comment by AaronSaikovski** [comment]
Will investigate.thanks

**Comment by bmanjwani** [comment]
Closing this issue. 
Please find the workaround in my above comment.
Moving forward, for further creates, We will be creating the CORS rule in CDN by default which will help us prevent CORS issue with CDN enabled sites.
