### ISSUE TITLE
Poor performance and unable to connect to JetPack

### ISSUE THREAD

**Issue by frasermclean** [Azure/wordpress-linux-appservice#54]
I recently migrated my personal blog from a CPanel hosting option to Azure. 

I have used the Bicep template as an example and deployed to Azure App Service, Storage Account and an Azure Front Door profile. I am experiencing very sluggish performance - particularly when viewing the site administration pages. Loading different pages can take quite a few seconds sometimes.

I also use the official JetPack plugin. It has very limited functionality with the new hosting setup and can't seem to connect to or read a lot of the site data. Do I need to enable any PHP extensions for this to work? What's the best way to troubleshoot this container image?

Not sure if I have something misconfigured or if this is expected behavior.

The site is [here](https://frasermclean.com)
The Bicep code is [here](https://github.com/frasermclean/personal-blog)

Any help would be appreciated!

**Comment by frasermclean** [comment]
Disabling the JetPack plugin seems to improve performance quite a bit. Just wondering if anyone could shed some light onto why this would be? JetPack is very useful in tracking visitor counts.

**Comment by AaronSaikovski** [comment]
are you able to quantify what you mean by sluggish performance? it could be the sku size of the app service or something isn't configured in AFD. Can you share some loadtest metrics such as mean latency etc?

**Comment by frasermclean** [comment]
Hi Aaron. It was taking upwards of 20 seconds to change between pages in the admin section. I checked the app service plan and the memory and CPU usage were acceptable. I found that disabling the JetPack plugin improved performance greatly. Seems to me like it might be a conflict between W3 Total cache plugin and JetPack although this is just speculation.

**Comment by AaronSaikovski** [comment]
interesting. ive found some of those caching plugins are more trouble than their worth sometimes. Total cache isn't too bad but with any major changes you have to flush the cache regularly. maybe disable both plugins and see if that fixes anything. good to hear its not the azure infra.

**Comment by frasermclean** [comment]
I believe the W3 Total cache is required by the docker image in order to store static content on the storage account. For my use case, JetPack is a must and it actually offers a free CDN. I am thinking of switching to the docker community image of WordPress and just using JetPack CDN instead of AFD.

**Comment by ZubaeyrMSFT** [comment]
HI @frasermclean, I would recommend you continue with our docker image as we have some performance optimizations lined up for release soon. You can simply remove W3TC plugin if it doesn't work for you. W3TC is used to configure local Redis caching, integrating Azure CDN/Front Door and also Azure Blob Storage.
