### ISSUE TITLE
Terraform missing data

### ISSUE THREAD

**Issue by The-Real-Adeel** [Azure/wordpress-linux-appservice#68]
Couple of things I want to bring light to while deploying this for our tenant. I compared the deployment done from azure portal's marketplace to see what was misaligned with what you have here.

1) The app service's app settings is missing data for front door:
AFD_ENABLED
AFD_ENDPOINT

2) Origins Groups does not include storage account's origin group

3) For resource "azurerm_cdn_frontdoor_rule" if you do have storage account...
    ["wp-content/uploads/"] does not include blob container  ie. ["<containerName>/wp-content/uploads/"]

**Comment by rabollin** [comment]
@AaronSaikovski - Would you be able to look into this issue.
