### ISSUE TITLE
ETA about PHP 8.2

### ISSUE THREAD

**Issue by mshyatsu** [Azure/wordpress-linux-appservice#73]
Hello, PHP 8.0 will be unsupported by November 2023. Do you have an ETA for PHP 8.2? Thanks.

**Comment by rabollin** [comment]
PHP8.2 support is in works and will be released in a month time.

**Comment by mshyatsu** [comment]
Thanks. I look forward to being available for PHP 8.2.

**Comment by rabollin** [comment]
@mshyatsu - We have test image available for php8.2; would you be able to do early validation with this image and provide any feedback
Image:  mcr.microsoft.com/appsvc/wordpress-alpine-php:8.2 

Tags list: https://mcr.microsoft.com/v2/appsvc/wordpress-alpine-php/tags/list

**Comment by rabollin** [comment]
Since it is already addressed, closing the issue
