### ISSUE TITLE
Can't browse wordpress @  https://mcr.microsoft.com

### ISSUE THREAD

**Issue by andycwk** [Azure/wordpress-linux-appservice#75]
Hi!

I've been trying to browse/find the wordpress container over at https://mcr.microsoft.com/ so I can review the available tags so I can lock down our install to a specific tag version but search shows a 404 while trying to navigate directly to https://mcr.microsoft.com/en-us/appsvc/wordpress-alpine-php 404s 👎 

Any thoughts or suggestions where I can review the available image tags?

**Comment by rabollin** [comment]
Hi currently - This is the URL you can use to get the list of tags: https://mcr.microsoft.com/v2/appsvc/wordpress-alpine-php/tags/list

**Comment by ZubaeyrMSFT** [comment]
@andycwk Alternatively, you can check our main documentation page for image and tags that we support.
https://github.com/Azure/wordpress-linux-appservice#image-details

**Comment by andycwk** [comment]
Sorry.. I've been on holiday and only just caught up on this stuff - thanks for all the help 🙏
