### ISSUE TITLE
Automatic updates for WordPress itself are not working/enabled currently

### ISSUE THREAD

**Issue by jmeddy** [Azure/wordpress-linux-appservice#76]
When signed into the site (wp-admin), going to Dashboard > Updates presents text under WordPress Updates" > Current Version denoting that automatic updates are not working/enabled currently: "This site will not receive automatic updates for new versions of WordPress." There is no clickable link for enabling automatic updates. This is a very important security requirement for utilizing this service. Note that this is not regarding auto updates for the App Service or the WordPress plugins as those both seem to work OK, just WordPress itself.

Note:
I did already email wordpressonazure@microsoft.com about this, and they responded with the following which directed me here: "There seem to be a bug with auto-upgrade configuration setting, sorry for the inconvenience caused. Can you please create a bug for the same here : [Issues · Azure/wordpress-linux-appservice (github.com)](https://github.com/Azure/wordpress-linux-appservice/issues), we will review and revert back once resolved."

![AzureAppService_WordPress_NoAutoUpdate](https://user-images.githubusercontent.com/21147207/234634752-1c14f3e1-519d-4c05-9768-05ed80e452e6.png)

**Comment by rabollin** [comment]
Thank you @jmeddy for creating the issue here. We are evaluating the fix for it and will keep you posted here.

**Comment by rabollin** [comment]
@jmeddy - this is fixed now; can you please try out creating the site with latest image in Marketplace and share any feedback you may have on the automatic upgrades?

**Comment by rabollin** [comment]
Closing the issue as this is supported now with the latest WordPress installations.
