### ISSUE TITLE
Default address range on WordPress on Azure

### ISSUE THREAD

**Issue by arjunbaliga** [Azure/wordpress-linux-appservice#82]
Default address range on WordPress on Azure. WordPress on Azure uses 10.0.0.0/16 as a default address range for VNET. this is a huge address range and 99.9% of customer cases they will not be able to integrate it with existing infrastructure. I'd like to raise as a product request. Can we consider a less range as a default one 10.0.0.0/24?

**Comment by arjunbaliga** [comment]
Hello @bmanjwani - Thank you for investigating this. I believe we should retain 10.0.0.0/16 as the default address range for the VNET. If customers encounter issues with this address range, they can consider changing it to 10.0.0.0/24. Please provide your suggestions.

**Comment by bmanjwani** [comment]
@arjunbaliga I agree to this. By default, we will keep the address range for the virtual network (VNet) as 10.0.0.0/16. This provides a broader range of IP addresses for potential use. However, if a customer wants a lesser range, they can consider having a custom address range for the VNet or subnet. This gives them the flexibility to choose a specific address range that suits their requirements.

**Comment by pmmota** [comment]
the issue about having a /16 network is that its almost impossible to peer the VNET with any existing infrastructure.
also nobody will create a wordpress environment that requires a /16 range, probably not even a /24 but at least a /24 is more compatible with other VNETs. In any case if the customers want to extend the /24 they can just create additional address ranges on the VNET, whereas its not impossible to reduce.

**Comment by bmanjwani** [comment]
@arjunbaliga @pmmota We have added it to our backlog and will address it as soon as we can. I will keep you informed about the progress and deployment of this change request.

**Comment by bmanjwani** [comment]
@arjunbaliga We have modified the default address range of vnet, change is deployed and available on production.
Current VNET range - /23
Db and App Subnet range - /25
