### ISSUE TITLE
Architecting Networking using this deployment (vnet integration)

### ISSUE THREAD

**Issue by The-Real-Adeel** [Azure/wordpress-linux-appservice#85]
Hi Team,

- App Service Plans have a one-to-one relation with a delegated subnet for vnet integration as a [limitation](https://learn.microsoft.com/en-us/azure/app-service/overview-vnet-integration#limitations).
- And you have an application setting called: WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED where you highly [recommend](https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_application_settings.md) keeping a single instance(no horizontal scaling). 

We are planning 20 independent sites at some point using your container deployment and we don't want a **single** instance shared to be a burden with the compute load for **all** sites, so we are thinking not to share the plan. So instead of 20 app services within a single app service plan. We are effectively having 20 app service plans with a single app service each, right?

But this means, we will be creating delegated subnets to have a one-to-one relationship a single app service plan. Resulting in 20 delegated subnets? 

What can be done to address this making so many subnets?

**Comment by rabollin** [comment]
HI @The-Real-Adeel If you are looking for deploying all your Apps in to same subnet range then we recommend following ARM template based deployment which will give you the flexibility to change SUBNET.  

Here is the ARM Script: https://github.com/Azure/wordpress-linux-appservice/tree/main/ARM_Template_Create_WP

**Comment by The-Real-Adeel** [comment]
That I can achieve, I am using terraform. 

I have two questions on this subject:

1) First I want confirmation. With this feature enabled (WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED) and having app service subnet delegation. I will not be able to do horizontal scaling as I can only have one instance right?  Meaning if I want twenty separate/unrelated sites within a single plan, I have to use a single compute instance?

2) Is the alternative if I want many sites to have independent compute resource to have multiple subnets **per** site?

**Comment by rabollin** [comment]
> That I can achieve, I am using terraform.
> 
> I have a few questions on this subject:
> 
> 1. First I want confirmation. With this feature enabled (WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED) and having subnet delegation for app service. I will not be able to do horizontal scaling as I can only have one instance right?  Meaning if I want twenty separate/unrelated sites within a single plan, I **have** to use a single compute instance?

Correct, currently if you have to use WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED; this works with single instance only and if you want to do horizontal scaling then you have to disable this caching.   At the moment we recommend to combine 3 to 5 sites to a single plan depending on the request volume.  For scaled-out environment, we do have a Dynamic caching feature getting ready to be deployed to production soon. 

> 2. Is the alternative if I want many sites to have independent compute resource to have multiple subnets **per** site?
You can have multiple sites in the same subnet, so while deploying the App service you specify the subnet you wanted to deploy to.  
> 3. What happens If I don't use WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED so I have a single app service plan with multiple sites using multiple computes. If so what is the behavior of having using WordPress with availability zones? Especially if I make edits/creating posts in WordPress, how does the replication to other instances occur if I am editing in the site itself rather than pushing code to ensure our customers see it on all zones they end up accessing?
WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED - this will help improve the site performance, if this is not there then there will be latency with WP Admin page loads.  Availability Zones will be helpful for securing your website from any datacenter impacts and it requires min. 3 instances of your app service : https://azure.github.io/AppService/2021/08/25/App-service-support-for-availability-zones.html; if you have to use Availability Zone for your site, then you must disable  local cache by setting this app setting WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED to false.

**Comment by ZubaeyrMSFT** [comment]
Hi @The-Real-Adeel

> Is the alternative if I want many sites to have independent compute resource to have multiple subnets per site?

No. Based on my understanding on how App Service Plan works, when you scale out an App Service Plan (ASP) to 2 instances, all the sites/apps within the ASP will be scaled out together to 2 instances. You cannot scale sites independently within an ASP. And I believe, subnets have nothing do with scaling out. We just have to ensure that subnet is large enough to accommodate all instances.
 

> What happens If I don't use WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED so I have a single app service plan with multiple sites using multiple computes. If so what is the behavior of having using WordPress with availability zones? Especially if I make edits/creating posts in WordPress, how does the replication to other instances occur if I am editing in the site itself rather than pushing code to ensure our customers see it on all zones they end up accessing?

a. I believe the deployment across availability zones will be taken care by App Service platform internally. Say, when you are scaled out to 3 instances, your app will be deployed in all 3 availability zones.
b. App Service uses a remote file storage. All the reads and writes happen directly to it. When you edit some files from one instance, you are making the change directly on remote file server. And when other instances read, they are reading from the remote file server. So, it will always be consistent. And this remote server has fail-over replica to avoid data loss.
c. If you don't use WORDPRESS_LOCAL_STORAGE_CACHE_ENABLED, you will be essentially using a remote file server, and performance might take a hit because of 'network latency' of remote IO operations.

**Comment by The-Real-Adeel** [comment]
Thank you for the insight. This can be closed.
