### ISSUE TITLE
Wordpress Updates

### ISSUE THREAD

**Issue by swt2c** [Azure/wordpress-linux-appservice#89]
Does Azure install updates to Wordpress Core automatically, or does that fall under customer responsibility?

My assumption would be that it would be customer responsibility, but this statement (from https://github.com/Azure/wordpress-linux-appservice/tree/main) leads me to believe otherwise:

"It also supports virtual networks, and the ability to run in an isolated and dedicated App Service Environment. **WordPress updates and patches**, threat detection and blocking, and traffic encryption with free SSL certificates are part of what we offer to all of our customers."

**Comment by samrueby** [comment]
It's customer responsibility. By default WordPress will update security patches and plugins automatically.

**Comment by swt2c** [comment]
> It's customer responsibility. By default WordPress will update security patches and plugins automatically.

OK.  I might suggest updating the documentation in bold to make that clearer.

**Comment by rabollin** [comment]
Thank you for the feedback, we will update the doc to reflect on what we actually support.  We support WordPress minor version upgrades out of the box however major versions are not. If customer opt-in for Major upgrade, then their sites can be auto migrated. Please find more details here: https://techcommunity.microsoft.com/t5/apps-on-azure-blog/how-to-keep-your-wordpress-website-stack-on-azure-app-service-up/ba-p/3832193

**Comment by rabollin** [comment]
Modified the text slightly to reflect the actual status.
