### ISSUE TITLE
Documentation showing how to deploy from GitHub Actions / Azure DevOps

### ISSUE THREAD

**Issue by swt2c** [Azure/wordpress-linux-appservice#90]
I think it would be useful to have some documentation or an example showing how to deploy Wordpress code updates via GitHub Actions and/or Azure DevOps.

**Comment by rabollin** [comment]
@swt2c - We will have this feature released in next few months providing out of the box ability for WP to deploy either from GH or DevOps.

**Comment by doodirock** [comment]
Is this out?

**Comment by rabollin** [comment]
@doodirock Yes, the feature is getting deployed to production environments and will be available in another 2 to 3 weeks. Will keep you posted on this issue.

**Comment by doodirock** [comment]
Awesome!

**Comment by communauto-asato** [comment]
> @doodirock Yes, the feature is getting deployed to production environments and will be available in another 2 to 3 weeks. Will keep you posted on this issue.

Do you happen to have any news on that? I see documentation about CI/CD, but no example exists.

**Comment by ZubaeyrMSFT** [comment]
Closing this thread as necessary documentation and feature for this is already out.

https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_azure_ci_cd.md
https://github.com/Azure/wordpress-linux-appservice/blob/main/WordPress/wordpress_azure_StageDeployments.md
