### ISSUE TITLE
PHP version not up to date

### ISSUE THREAD

**Issue by pamapa** [Azure/wordpress-linux-appservice#97]
appsvc/wordpress-alpine-php 8.2 is using PHP 8.2.5, but PHP 8.2.8 is currently the latest one, would nice if you could update the docker image.
Also appsvc/wordpress-alpine-php 8.0 is not up to date.

PS: Where is the docker file (Dockerfile) of those images located at? Would be nice if you could add a link in the README.md.

**Comment by rabollin** [comment]
@pamapa - the latest version of PHP8.2 & 8.0 images will be refreshed in production by end of this week. Please watch out for the upgrades.

**Comment by pamapa** [comment]
docker image with latest PHP 8.2.9 arrived. Thanks for updating!

**Comment by PatrykPlewaOfficial** [comment]
@rabollin Could you please add the source Dockerfile to this repo?

**Comment by sshibily** [comment]
@rabollin Can you add the source for the Dockerfile?
